### ISSUE TITLE
Error when writing image

### ISSUE THREAD

**Issue by axk4545** [MartinBriza/MediaWriter#70] opened 2017-03-13 15:45 UTC
When I run the mediawriter tool as root through terminal on Fedora 25 64bit and pick my own iso to write I get the following error after clicking write:
Warning: Writing failed: "Message recipient disconnected from message bus without replying" ((null):0, (null))
Please let me know if you need any further information.

**Comment by MartinBriza** [comment] 2017-03-13 15:46
Mediawriter is not intended to be ran as root. Please report if that issue happens if you use your regular user, too.

**Comment by axk4545** [comment] 2017-03-13 15:49
@MartinBriza I just attempted to run it as a normal user and I am now getting this error:
Warning: Writing failed: "Not authorized to perform operation" ((null):0, (null))

**Comment by MartinBriza** [comment] 2017-03-13 15:50
Is polkit and dbus running on your system?

**Comment by MartinBriza** [comment] 2017-03-13 15:57
Thinking about it, a polkit agent probably isn't running on your system.

**Comment by axk4545** [comment] 2017-03-13 22:11
@MartinBriza I enabled a polkit agent and received the auth prompt but I am receiving the "Message recipient disconnected from message bus without replying" error again. how can I check whether DBUS is running?

**Comment by MartinBriza** [comment] 2017-03-14 08:29
`systemctl status dbus.service`, however if you see drives in the UI, it's running.
What system configuration are you running on? Which DE? How did you install it? What changes did you do to the configuration?

**Comment by MartinBriza** [comment] 2017-03-21 09:02
It's been a week since last answer and I'm fairly certain the problem is caused by your system configuration so I'll just close this bug. However, if you still suffer from this or any other issue or just want to help find what's wrong with your configuration, please go ahead and contact me, even privately, I'm completely okay with that and I'll help you.

**Closed by MartinBriza** 2017-03-21 09:02 UTC
