### ISSUE TITLE
mediawriter cannot run in windows xp

### ISSUE THREAD

**Issue by jackjack0040** [MartinBriza/MediaWriter#52] opened 2016-12-26 05:33 UTC
http://imgur.com/a/01aXR

I downloaded fedora mediawriter in windows xp in my computer, setup it in c:/. and this message told me it cannot run. Why?

**Comment by MartinBriza** [comment] 2017-01-03 16:31
Yes, thanks for the report. Currently, we don't support Windows XP in Fedora Media Writer. However, this bug could be caused by some other issue (FMW doesn't start for some folks on Windows 7 with a similar error message). I'll work on fixing that other problem and that may fix the issue for you.

Generally, I'm not looking to commit time to work on supporting a deprecated system though, I'm sorry.

**Comment by MartinBriza** [comment] 2017-03-21 09:23
Can you please try running the 4.0.95 (or a newer) version from Releases and eventually if it crashes, post your C:\Documents and Settings\<your user>\My Documents\FedoraMediaWriter.log file here?

**Comment by jackjack0040** [comment] 2017-03-23 13:42
thanks...I will try if I have time...but I take more time to work  in high
work time, so maybe you wait several weeks for this result, and I have used
rufus to make fedora usb live cd...
http://www.toptrix.net/2012/03/bootable-usb-making-tools-windows-linux.html

明孝敬啟
觀自在菩薩，行深般若波羅密多時，照見五蘊皆空，度一切苦厄，舍利子。

2017-03-21 17:23 GMT+08:00 Martin Bříza <notifications@github.com>:

**Comment by MartinBriza** [comment] 2017-08-30 15:39
Could be fixed by 8f6c16d1adbcf15c4319953259e76d7e70c85951. We need to test it with 4.1.1 when it comes out.

**Comment by truboxl** [comment] 2018-01-29 10:16
Since I have plenty of time to do useless stuff, I try testing out...
Tested on Windows Virtual PC XP Mode

4.0.8
- No FedoraMediaWriter.log
- Plain crash Visual C++ error as expected by driver problem

4.0.9.5
- A quick see through FMW window flash by
- There is FedoraMediaWriter.log though
> D@62ms: Application constructed
D@63ms: Injecting QML context properties
D@69ms: WinDriveProvider construction
D@69ms: DriveManager construction
D@73ms: ReleaseManager construction
D@74ms: ReleaseManager Received a metadata json
D@75ms: ReleaseManager Adding "workstation" "25" "x86_64"
D@75ms: ReleaseManager Adding "workstation" "25" "i386"
D@76ms: ReleaseManager Adding "workstation" "25" "armhfp"
D@76ms: ReleaseManager Adding "server" "25" "x86_64"
D@76ms: ReleaseManager Adding "server" "25" "i386"
D@76ms: ReleaseManager Adding "server" "25" "armhfp"
D@76ms: ReleaseManager Adding "astronomy" "25" "x86_64"
D@76ms: ReleaseManager Adding "design suite" "25" "x86_64"
D@76ms: ReleaseManager Adding "games" "25" "x86_64"
D@77ms: ReleaseManager Adding "jam" "25" "x86_64"
D@77ms: ReleaseManager Adding "robotics" "25" "x86_64"
D@77ms: ReleaseManager Adding "scientific" "25" "x86_64"
D@77ms: ReleaseManager Adding "security" "25" "x86_64"
D@77ms: ReleaseManager Adding "astronomy" "25" "i386"
D@77ms: ReleaseManager Adding "design suite" "25" "i386"
D@77ms: ReleaseManager Adding "games" "25" "i386"
D@77ms: ReleaseManager Adding "jam" "25" "i386"
D@77ms: ReleaseManager Adding "robotics" "25" "i386"
D@77ms: ReleaseManager Adding "scientific" "25" "i386"
D@77ms: ReleaseManager Adding "security" "25" "i386"
D@78ms: ReleaseManager Adding "cinnamon" "25" "x86_64"
D@78ms: ReleaseManager Adding "kde" "25" "x86_64"
D@78ms: ReleaseManager Adding "lxde" "25" "x86_64"
D@78ms: ReleaseManager Adding "mate" "25" "x86_64"
D@78ms: ReleaseManager Adding "soas" "25" "x86_64"
D@78ms: ReleaseManager Adding "xfce" "25" "x86_64"
D@78ms: ReleaseManager Adding "cinnamon" "25" "i386"
D@78ms: ReleaseManager Adding "kde" "25" "i386"
D@78ms: ReleaseManager Adding "lxde" "25" "i386"
D@78ms: ReleaseManager Adding "mate" "25" "i386"
D@79ms: ReleaseManager Adding "soas" "25" "i386"
D@79ms: ReleaseManager Adding "xfce" "25" "i386"
D@79ms: ReleaseManager Adding "kde" "25" "armhfp"
D@79ms: ReleaseManager Adding "lxde" "25" "armhfp"
D@79ms: ReleaseManager Adding "mate" "25" "armhfp"
D@79ms: ReleaseManager Adding "soas" "25" "armhfp"
D@79ms: ReleaseManager Adding "xfce" "25" "armhfp"
D@79ms: ReleaseManager Adding "workstation" "24" "x86_64"
D@79ms: ReleaseManager Adding "workstation" "24" "i386"
D@79ms: ReleaseManager Adding "server" "24" "x86_64"
D@79ms: ReleaseManager Adding "kde" "24" "x86_64"
D@80ms: ReleaseManager Adding "kde" "24" "i386"
D@80ms: ReleaseManager Adding "xfce" "24" "x86_64"
D@80ms: ReleaseManager Adding "xfce" "24" "i386"
D@80ms: ReleaseManager Adding "lxde" "24" "x86_64"
D@80ms: ReleaseManager Adding "lxde" "24" "i386"
D@80ms: ReleaseManager Adding "mate" "24" "x86_64"
D@80ms: ReleaseManager Adding "mate" "24" "i386"
D@80ms: ReleaseManager Adding "cinnamon" "24" "x86_64"
D@80ms: ReleaseManager Adding "cinnamon" "24" "i386"
D@80ms: ReleaseManager Adding "soas" "24" "x86_64"
D@80ms: ReleaseManager Adding "soas" "24" "i386"
D@81ms: ReleaseManager Adding "astronomy" "24" "x86_64"
D@81ms: ReleaseManager Adding "astronomy" "24" "i386"
D@81ms: ReleaseManager Adding "design" "24" "x86_64"
D@81ms: ReleaseManager Adding "design" "24" "i386"
D@81ms: ReleaseManager Adding "games" "24" "x86_64"
D@81ms: ReleaseManager Adding "games" "24" "i386"
D@81ms: ReleaseManager Adding "robotics" "24" "x86_64"
D@81ms: ReleaseManager Adding "robotics" "24" "i386"
D@81ms: ReleaseManager Adding "scientific" "24" "x86_64"
D@81ms: ReleaseManager Adding "scientific" "24" "i386"
D@82ms: ReleaseManager Adding "security" "24" "x86_64"
D@82ms: ReleaseManager Adding "security" "24" "i386"
D@89ms: VersionChecker Asking for new FMW version information
D@263ms: Download Trying to download from a mirror: QUrl("https://getfedora.org/static/fmw-version.json")
D@264ms: Loading the QML source code
D@2053ms: Starting the application
D@2053ms: WinDriveProvider Looking for the drives for the first time
W@2053ms: Could not get disk extents for "\\\\.\\A:"
W@2053ms: Could not get disk extents for "\\\\.\\D:"
D@2053ms: WinDriveProvider Finished looking at drive letters
D@2054ms: WinDriveProvider "\\\\.\\PhysicalDrive0" is present
D@2054ms: WinDriveProvider "\\\\.\\PhysicalDrive0" IOCTL_STORAGE_QUERY_PROPERTY
D@2054ms: WinDriveProvider "\\\\.\\PhysicalDrive0" IOCTL_STORAGE_QUERY_PROPERTY with a bigger buffer
D@2054ms: WinDriveProvider "\\\\.\\PhysicalDrive0" detected: "" "Virtual HD" , nonremovable notUSB
D@2054ms: WinDriveProvider Finished looking for the drives for the first time
D@2055ms: Download Trying to download from a mirror: QUrl("https://getfedora.org/releases.json")
W@2055ms: Error reading from QUrl("https://getfedora.org/static/fmw-version.json") : "Unknown error"
W@2055ms: SSL error "The issuer certificate of a locally looked up certificate could not be found"
W@2055ms: VersionChecker It was impossible to fetch info about a new FMW version: "Unknown error"
C@2084ms: === CRASH OCCURED ===
C@2084ms: An unhandled exception occurred:
C@2084ms: Code: -1073741819 - ACCESS VIOLATION
C@2084ms: Flags: 0
C@2084ms: Address 0x0
C@2206ms: Backtrace:
W@2207ms: QObject::~QObject: Timers cannot be stopped from another thread
W@2220ms: QWaitCondition: Destroyed while threads are still waiting

Running [Root Certificate Updater](https://msfn.org/board/topic/175170-root-certificates-and-revoked-certificates-for-windows-xp/?page=3&tab=comments#comment-1110568) seems to fix the download and SSL errors but the same crash remains...

4.1.0
- Same see through window in 4.0.95 flash by but no FedoraMediaWriter.log found

4.1.1
- No FedoraMediaWriter.log found
- No flashing window but here's an error
![image](https://user-images.githubusercontent.com/12658589/35497817-c6ac7e8c-0506-11e8-8129-a9f2b4824838.png)
- Looks like CancelIOEx problem is [reported already](https://github.com/MartinBriza/MediaWriter/issues/21#issuecomment-280183208), but I cannot replicate it in 4.0.8, stopped by the Visual C++ error
- The reported missing function probably related to the crash in earlier builds

Verdict
- XP expiring Root Certificates will be a problem to get releases info online, MSFT stopped making downloadable updates (rootsupd.exe), people have to resort to unofficial tools or update manually
- Maybe use workaround on Qt to not use Vista+ functions? (eg: CancelIOEx)
- Suggest use Rufus instead? Rufus is dropping XP support too after 2.18
- IE8 on XP can't even open https://getfedora.org and [various websites](https://www.bleepingcomputer.com/forums/t/631486/ie8-wont-display-microsoft-https-sites/), Firefox and others are ok

**Comment by MartinBriza** [comment] 2018-01-31 17:08
Thank you for the extensive investigation. I've checked a few sources on this and searched for the source of your error message in 4.1.1. I have to conclude with the statement this is not fixable. 
I never intended to support Windows XP in Fedora Media Writer and while I thought running it in Windows XP may be possible, now I'm sure it is not and never will be. Qt stopped oficially supporting XP a long time ago and with 5.8 and above there are runtime dependencies on functions not implemented in kernel32.dll in Windows XP (FMW is now based on Qt 5.9.1).
I'm sorry about this but supporting this outdated operating system is above and beyond the time I can dedicate to the FMW development. I suggest you to upgrade to a newer OS.

**Closed by MartinBriza** 2018-01-31 17:08 UTC

**Comment by jackjack0040** [comment] 2018-02-06 10:06
thx...I have this problem for one year...but I throw it to trash can and
decide to not mind it...I have bougjt a new notebooke in windows10 six
months ago. I will have a vacation of Spring Holiday and I wana try
scientific linux in computer. God bless you!

明孝敬啟
觀自在菩薩，行深般若波羅密多時，照見五蘊皆空，度一切苦厄，舍利子。

2018-02-01 1:08 GMT+08:00 Martin Bříza <notifications@github.com>:
