### ISSUE TITLE
Fedora Media Writer Graphical Corruption Windows 7

### ISSUE THREAD

**Issue by fiddybux** [MartinBriza/MediaWriter#108] opened 2017-08-25 07:59 UTC
[http://imgur.com/a/5iGnZ](url)

Don't know how else to explain it...it's just fuzzy, but readable. Works fine otherwise.

Windows 7, Lenovo T500, Intel Graphics.

**Comment by MartinBriza** [comment] 2017-08-29 11:35
Duplicate of #97

**Closed by MartinBriza** 2017-08-29 11:35 UTC
Labels: duplicate
